/*
 * This source file was generated by the Gradle 'init' task
 */
package uk.co.matchboard.app;

import org.junit.jupiter.api.Test;

import uk.co.matchboard.app.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
